Repository cjolowicz/cookiecutter-hypermodern-python-instance, pull requests merged in 2021-11, with the labels that each got.

#664 👷 [github] Use Python 3.10 on Windows and macOS in Tests workflow
  .github/workflows/tests.yml
Labels: ci

#675 📦 [poetry] Avoid semver constraints for dependencies using CalVer
  poetry.lock
  pyproject.toml
Labels: dependencies

#676 📚 Use furo Sphinx theme for documentation
  docs/conf.py
  docs/reference.rst
  docs/requirements.txt
  noxfile.py
  poetry.lock
  pyproject.toml
Labels: documentation

#697 Update test GA workflow for more consistent style
  .github/workflows/tests.yml
Labels: ci

#698 👷 [readthedocs] Use Python 3.10 on Read the Docs
  .readthedocs.yml
Labels: ci

#699 👷 [github] Shorten `python-version` to `python` in Tests workflow matrix
  .github/workflows/tests.yml
Labels: ci

#700 👷 [github] Enable colors from pre-commit, pytest, Sphinx, and xdoctest
  .github/workflows/tests.yml
  noxfile.py
Labels: ci

#545 Include test suite in code coverage
  pyproject.toml
Labels: testing

#710 👷 [nox] Combine coverage under the latest Python release
  noxfile.py
Labels: ci

#711 🔨 [nox] Do not hardcode Python versions in `@session` decorators
  noxfile.py
Labels: ci
